baseURL = "https://robotdesign.net/"
locale = "en"
title = "Robotdesign.net"

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[params]
  mainSections = ["posts"]

[params.homepage]
  layout = "background"
  showRecent = true
